### ISSUE TITLE
Support Fluent 3D

### ISSUE THREAD

**Issue by aaronliu0130** [MiniDiscordThemes/EmojiReplace#1]
**Describe the solution you'd like**
Support https://emojipedia.org/microsoft-3D-fluent emojis

**Describe alternatives you've considered**
Replace the 2D fluent emojis with 3D ones

**Additional context**
In 23H2, Microsoft rolled out 3D emojis to apps like Firefox, Notepad and PowerPoint.

*shamelessly copied from mwittrien/BetterDiscordAddons#2551*

**Comment by Saltssaumure** [comment]
No ETA at present but in progress 👍

**Comment by aaronliu0130** [comment]
Could this be copied from DevilBro now that they have implemented it?

**Comment by Saltssaumure** [comment]
Sure, I'll take a look as soon as I can.

**Comment by Saltssaumure** [comment]
Completed in v1.3.0
