### ISSUE TITLE
Vencord Support

### ISSUE THREAD

**Issue by D3SOX** [MiniDiscordThemes/EmojiReplace#2]
Is it possible to make this compatible with Vencord? I was trying to compile the CSS to a theme file and played around with it, but I couldn't get it to work.

For example:
In Discord: `<img aria-label="🤮" src="/assets/bacbd2479dd718ffa2ae.svg" alt="🤮" draggable="false" class="emoji" data-type="emoji" data-name=":face_vomiting:">`

but I couldn't find `bacbd2479dd718ffa2ae` in the source. Is the `scss/vars/_emojis.scss` up to date with latest Discord stable?

**Comment by aaronliu0130** [comment]
For Vencord and BD (and Shelter) just use DevilBro's.

**Comment by D3SOX** [comment]
DevilBro's uses an outdated version of JoyPixels and this one is up to date with version 8 as far as I can tell

**Comment by aaronliu0130** [comment]
File an issue with DevilBro then

**Comment by D3SOX** [comment]
Already did months ago and he said he no longer maintains it.

**Comment by aaronliu0130** [comment]
(DevilBro is fixed now, see https://github.com/mwittrien/BetterDiscordAddons/issues/2477)

**Comment by Saltssaumure** [comment]
My version is a port of DevilBro's, so both should have the same images.

**Comment by D3SOX** [comment]
Oh okay so then I guess you should update yours now as DevilBro just pushed the new version :tada:
