### ISSUE TITLE
Support super emojis

### ISSUE THREAD

**Issue by aaronliu0130** [MiniDiscordThemes/EmojiReplace#3]
Currently, when a super emoji's animation plays, the emoji is still in Twemoji. It suddenly goes to the replaced version after the animation ends. I hope EmojiReplace can replace that.

**Comment by Saltssaumure** [comment]
Doesn't seem to be possible - the animation places the emoji as an `<image>` inside an SVG, which cannot be directly changed with CSS.

**Comment by aaronliu0130** [comment]
Could a plugin be made for this, perhaps?

**Comment by Saltssaumure** [comment]
That would be the ideal solution. Try putting in a suggestion in the
replugged-org/addon-requests repo.
